### ISSUE TITLE
how to call destruct

### ISSUE THREAD

**Issue by SuelTheDev** [ImagicTheCat/Luaoop#14]
How to call destruct method? I try to call, but the method is always nil.

**Comment by ImagicTheCat** [comment]
> An instance inherits from its class fields (with inheritance), except for xtype_*, luaoop and those starting with __, which are special class fields.

Alternatively, you can do `Class.__destruct(instance)`.

**Comment by SuelTheDev** [comment]
> > An instance inherits from its class fields (with inheritance), except for xtype_*, luaoop and those starting with __, which are special class fields.
> 
> Alternatively, you can do `Class.__destruct(instance)`.

Thank you! Worked perfect.
