### ISSUE TITLE
class.instanceof for derived class does not working.

### ISSUE THREAD

**Issue by MikuAuahDark** [ImagicTheCat/Luaoop#2]
```lua
a = class("A")
b = class("B", a)

inst = b()
print(class.instanceof(inst, "A")) -- false
```
Is that intended? or is it a bug?

**Comment by ImagicTheCat** [comment]
It's a bug, thanks for reporting it.
I changed the way inheritance was working but I forgot to rewrite some functions depending on the old way. I will rewrite everything soon.

**Comment by MikuAuahDark** [comment]
Alright it's good to know.

**Comment by ImagicTheCat** [comment]
Should be fixed, https://github.com/ImagicTheCat/Luaoop/commit/8fcb4a1f66783cc4e7bdbf3b57753ba41c3cc417 . You can use the scm version/standalone file until the next release.
