### ISSUE TITLE
attempt to read undeclared variable 'meta' (strict.lua)

### ISSUE THREAD

**Issue by MikuAuahDark** [ImagicTheCat/Luaoop#4]
It seems happen when I define a destructor for my class.

https://github.com/ImagicTheCat/Luaoop/blob/f33e036dec95166d276648888ab7b5251dcf778c/src/Luaoop.lua#L361

**Comment by ImagicTheCat** [comment]
Thanks for the bug report, should be fixed by https://github.com/ImagicTheCat/Luaoop/commit/163db55838d0be408350d8d23dc7641a82b95460.
