### ISSUE TITLE
Checking if a table is a class definition

### ISSUE THREAD

**Issue by AntonC9018** [ImagicTheCat/Luaoop#9]
Is there a way of checking if a given table is a class or an instance? I came up with this through some experimentation:
```lua
local function is_class(t)
    local mt = getmetatable(t)
    if mt ~= nil then 
        return mt.luaoop.type == nil
    end
    return false
end
```

**Comment by ImagicTheCat** [comment]
I should have added some patterns like that in the doc:
- class or instance: `class.type(t) ~= nil` , `class.name(t) ~= nil`, etc.
- class: `class.type(t) == t`

**Comment by AntonC9018** [comment]
Thanks, this makes sense.
